version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  # app:
    # build: .
    # depends_on:
    #   - db
    # ports:
    #   - "8000:8000"
    # environment:
    #   DATABASE_URL: postgresql://postgres:admin123@localhost:5432/database

volumes:
  pgdata:


# version: '3.8'
# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root1234
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     ports:
#       - 5100:5432
  
#   volumes:
#   postgres_data:




