"""Database modified

Revision ID: 1df05dd39343
Revises: a2c89c4235c7
Create Date: 2024-07-25 14:56:15.928815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df05dd39343'
down_revision: Union[str, None] = 'a2c89c4235c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.add_column('blog', sa.Column('image_paths', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'image_paths')
    op.create_table('image',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.blog_id'], name='image_blog_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name='image_pkey')
    )
    # ### end Alembic commands ###
