"""move images into blog table

Revision ID: 587fee56cdd7
Revises: e3e1f08db4a1
Create Date: 2024-07-26 09:41:17.285953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587fee56cdd7'
down_revision: Union[str, None] = 'e3e1f08db4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.add_column('blog', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'images')
    op.create_table('image',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.blog_id'], name='image_blog_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name='image_pkey')
    )
    # ### end Alembic commands ###
