"""Database modified

Revision ID: 94691cc5ff03
Revises: 1df05dd39343
Create Date: 2024-07-25 15:17:21.024465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94691cc5ff03'
down_revision: Union[str, None] = '1df05dd39343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image', sa.String(length=255), nullable=True))
    op.drop_column('blog', 'image_paths')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image_paths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('blog', 'image')
    # ### end Alembic commands ###
